-- Rev 6: agent-contact tags, company families, dedup queue, company-level lease links.
-- Additive. Does not alter accounts, master_leases, riders, or railcars columns.
-- Does not auto-merge any companies.

CREATE OR REPLACE FUNCTION public.clean_company_name(p_name text)
RETURNS text
LANGUAGE sql
IMMUTABLE
AS $$
  SELECT regexp_replace(
    regexp_replace(
      regexp_replace(
        lower(regexp_replace(coalesce(p_name, ''), '&', ' and ', 'g')),
        '[^a-z0-9]+', ' ', 'g'
      ),
      '\m(incorporated|corporation|company|limited|the|inc|llc|llp|corp|ltd|lp|plc|sa|co)\M',
      '',
      'g'
    ),
    '\s+',
    '',
    'g'
  );
$$;

ALTER TABLE public.company_contacts
  ADD COLUMN IF NOT EXISTS is_agent_contact boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS agent_organization_name text,
  ADD COLUMN IF NOT EXISTS agent_home_company_id bigint REFERENCES public.companies(id);
CREATE INDEX IF NOT EXISTS idx_company_contacts_is_agent
  ON public.company_contacts(is_agent_contact) WHERE is_agent_contact;

ALTER TABLE public.companies
  ADD COLUMN IF NOT EXISTS family_parent_id bigint REFERENCES public.companies(id);
ALTER TABLE public.companies
  DROP CONSTRAINT IF EXISTS companies_family_parent_not_self;
ALTER TABLE public.companies
  ADD CONSTRAINT companies_family_parent_not_self CHECK (family_parent_id IS DISTINCT FROM id);
CREATE INDEX IF NOT EXISTS idx_companies_family_parent
  ON public.companies(family_parent_id) WHERE family_parent_id IS NOT NULL;

DO $$ BEGIN
  CREATE TYPE public.dedup_candidate_kind AS ENUM ('agent_contact', 'company_family', 'company_duplicate');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
DO $$ BEGIN
  CREATE TYPE public.dedup_candidate_status AS ENUM ('auto_applied', 'pending_review', 'approved', 'rejected');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

CREATE TABLE IF NOT EXISTS public.contact_company_dedup_candidates (
  id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kind                    public.dedup_candidate_kind NOT NULL,
  company_contact_id      bigint REFERENCES public.company_contacts(id) ON DELETE CASCADE,
  agent_organization_name text,
  agent_home_company_id   bigint REFERENCES public.companies(id),
  company_id_a            bigint REFERENCES public.companies(id),
  company_id_b            bigint REFERENCES public.companies(id),
  email                   text,
  signal                  text NOT NULL,
  confidence              numeric,
  note                    text,
  status                  public.dedup_candidate_status NOT NULL DEFAULT 'pending_review',
  reviewed_by             uuid REFERENCES auth.users(id),
  reviewed_at             timestamptz,
  created_at              timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_dedup_candidates_status ON public.contact_company_dedup_candidates(status);
CREATE INDEX IF NOT EXISTS idx_dedup_candidates_kind ON public.contact_company_dedup_candidates(kind);

ALTER TABLE public.contact_lease_links
  ALTER COLUMN company_contact_id DROP NOT NULL;
ALTER TABLE public.contact_lease_links
  ADD COLUMN IF NOT EXISTS company_id bigint REFERENCES public.companies(id) ON DELETE CASCADE;
ALTER TABLE public.contact_lease_links
  DROP CONSTRAINT IF EXISTS contact_lease_links_linked_entity;
ALTER TABLE public.contact_lease_links
  ADD CONSTRAINT contact_lease_links_linked_entity CHECK (
    (company_contact_id IS NOT NULL AND company_id IS NULL)
    OR (company_contact_id IS NULL AND company_id IS NOT NULL)
  );
CREATE INDEX IF NOT EXISTS idx_contact_lease_links_company
  ON public.contact_lease_links(company_id) WHERE company_id IS NOT NULL;
