-- Unified activity / lineage log for railcars and riders.
-- Specialized tables (car_number_history, assignment_history, car_status_history,
-- rent_events) stay as sources of truth; this table is the merged, queryable feed.

CREATE TABLE IF NOT EXISTS public.activity_log (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entity_type text NOT NULL,
  entity_id bigint NOT NULL,
  railcar_id bigint REFERENCES public.railcars (id) ON DELETE SET NULL,
  rider_id bigint REFERENCES public.riders (id) ON DELETE SET NULL,
  action text NOT NULL,
  detail jsonb NOT NULL DEFAULT '{}'::jsonb,
  actor text,
  source text NOT NULL DEFAULT 'ui',
  occurred_at timestamptz NOT NULL DEFAULT now(),
  created_at timestamptz NOT NULL DEFAULT now(),
  source_table text,
  source_id bigint,
  CONSTRAINT activity_log_entity_type_check
    CHECK (entity_type = ANY (ARRAY['railcar'::text, 'rider'::text]))
);

CREATE INDEX IF NOT EXISTS idx_activity_log_railcar_occurred
  ON public.activity_log (railcar_id, occurred_at DESC)
  WHERE railcar_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_activity_log_rider_occurred
  ON public.activity_log (rider_id, occurred_at DESC)
  WHERE rider_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_activity_log_entity
  ON public.activity_log (entity_type, entity_id, occurred_at DESC);

CREATE INDEX IF NOT EXISTS idx_activity_log_occurred
  ON public.activity_log (occurred_at DESC);

CREATE UNIQUE INDEX IF NOT EXISTS uq_activity_log_source_row
  ON public.activity_log (source_table, source_id)
  WHERE source_table IS NOT NULL AND source_id IS NOT NULL;

COMMENT ON TABLE public.activity_log IS
  'Append-only lineage for cars and riders: mark changes, status, rent, assignments, notes.';

-- Reporting mark / number changes (including VCF remarks — those are real lineage)
INSERT INTO public.activity_log (
  entity_type, entity_id, railcar_id, action, detail, actor, source, occurred_at, source_table, source_id
)
SELECT
  'railcar',
  h.railcar_id,
  h.railcar_id,
  'mark_change',
  jsonb_strip_nulls(jsonb_build_object(
    'from', NULLIF(trim(concat_ws(' ', h.old_car_initial, h.old_car_number)), ''),
    'to', NULLIF(trim(concat_ws(' ', h.new_car_initial, h.new_car_number)), ''),
    'reason', h.reason
  )),
  COALESCE(h.changed_by, 'system'),
  CASE WHEN h.changed_by = 'vcf-import' THEN 'vcf-import' ELSE 'ui' END,
  COALESCE(h.changed_at, now()),
  'car_number_history',
  h.id
FROM public.car_number_history h
WHERE h.railcar_id IS NOT NULL
  AND NOT EXISTS (
    SELECT 1 FROM public.activity_log a
    WHERE a.source_table = 'car_number_history' AND a.source_id = h.id
  );

-- Active status Inactive / Reactivate
INSERT INTO public.activity_log (
  entity_type, entity_id, railcar_id, action, detail, actor, source, occurred_at, source_table, source_id
)
SELECT
  'railcar',
  h.car_id,
  h.car_id,
  'status_change',
  jsonb_strip_nulls(jsonb_build_object(
    'event_type', h.event_type,
    'from', h.from_status,
    'to', h.to_status,
    'reason', h.reason
  )),
  h.created_by,
  'ui',
  h.created_at,
  'car_status_history',
  h.id
FROM public.car_status_history h
WHERE h.car_id IS NOT NULL
  AND NOT EXISTS (
    SELECT 1 FROM public.activity_log a
    WHERE a.source_table = 'car_status_history' AND a.source_id = h.id
  );

-- On / off rent
INSERT INTO public.activity_log (
  entity_type, entity_id, railcar_id, action, detail, actor, source, occurred_at, source_table, source_id
)
SELECT
  'railcar',
  e.car_id,
  e.car_id,
  'rent_event',
  jsonb_strip_nulls(jsonb_build_object(
    'event_type', e.event_type,
    'event_date', e.event_date,
    'reason', e.reason
  )),
  e.created_by,
  'ui',
  COALESCE(e.event_date::timestamptz, e.created_at, now()),
  'rent_events',
  e.id
FROM public.rent_events e
WHERE e.car_id IS NOT NULL
  AND NOT EXISTS (
    SELECT 1 FROM public.activity_log a
    WHERE a.source_table = 'rent_events' AND a.source_id = e.id
  );

-- Real assignment / Move Cars rows only — skip VCF period placeholders
INSERT INTO public.activity_log (
  entity_type, entity_id, railcar_id, rider_id, action, detail, actor, source, occurred_at, source_table, source_id
)
SELECT
  'railcar',
  h.railcar_id,
  h.railcar_id,
  h.to_rider_id,
  'reassignment',
  jsonb_strip_nulls(jsonb_build_object(
    'from_rider_id', h.from_rider_id,
    'to_rider_id', h.to_rider_id,
    'from_fleet', h.from_fleet_name,
    'to_fleet', h.to_fleet_name,
    'reason', h.reason
  )),
  COALESCE(h.moved_by, 'system'),
  'ui',
  COALESCE(h.moved_at, now()),
  'assignment_history',
  h.id
FROM public.assignment_history h
WHERE h.railcar_id IS NOT NULL
  AND COALESCE(h.moved_by, '') <> 'vcf-import'
  AND COALESCE(h.reason, '') NOT ILIKE '%V_VALID_CARS assignment period%'
  AND NOT EXISTS (
    SELECT 1 FROM public.activity_log a
    WHERE a.source_table = 'assignment_history' AND a.source_id = h.id
  );

-- Legacy single-field railcar notes → one timestamped entry each
INSERT INTO public.activity_log (
  entity_type, entity_id, railcar_id, action, detail, actor, source, occurred_at, source_table, source_id
)
SELECT
  'railcar',
  r.id,
  r.id,
  'note',
  jsonb_build_object('body', r.notes),
  'legacy',
  'legacy',
  COALESCE(r.updated_at, now()),
  'railcars.notes',
  r.id
FROM public.railcars r
WHERE r.notes IS NOT NULL AND btrim(r.notes) <> ''
  AND NOT EXISTS (
    SELECT 1 FROM public.activity_log a
    WHERE a.source_table = 'railcars.notes' AND a.source_id = r.id
  );

-- Legacy rider notes
INSERT INTO public.activity_log (
  entity_type, entity_id, rider_id, action, detail, actor, source, occurred_at, source_table, source_id
)
SELECT
  'rider',
  r.id,
  r.id,
  'note',
  jsonb_build_object('body', r.notes),
  'legacy',
  'legacy',
  COALESCE(r.updated_at, now()),
  'riders.notes',
  r.id
FROM public.riders r
WHERE r.notes IS NOT NULL AND btrim(r.notes) <> ''
  AND NOT EXISTS (
    SELECT 1 FROM public.activity_log a
    WHERE a.source_table = 'riders.notes' AND a.source_id = r.id
  );
