-- Programs rebuild: extend stub tables, add categories/field defs/shops/scrap
-- yards/car-line documents/activity. Tables are empty in prod today.
-- Safe to re-run.

-- ── Lookups ──────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.program_categories (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL UNIQUE,
  description text,
  sort_order int NOT NULL DEFAULT 0,
  active boolean NOT NULL DEFAULT true
);

CREATE TABLE IF NOT EXISTS public.shops (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  location text,
  shop_type text,
  tank_labor_rate numeric,
  freight_labor_rate numeric,
  switch_fees numeric,
  address text,
  serving_rr text,
  connecting_rr text,
  admin_contact_name text,
  admin_contact_email text,
  admin_contact_office text,
  admin_contact_cell text,
  commercial_contact_name text,
  commercial_contact_email text,
  commercial_contact_office text,
  commercial_contact_cell text
);

CREATE TABLE IF NOT EXISTS public.scrap_yards (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  location text,
  rate_per_gross_ton numeric,
  serving_rr text,
  connecting_rr text,
  address text,
  contact_name text,
  contact_email text,
  contact_office text,
  contact_cell text
);

CREATE TABLE IF NOT EXISTS public.program_field_defs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_id bigint NOT NULL REFERENCES public.program_categories(id) ON DELETE CASCADE,
  field_key text NOT NULL,
  label text NOT NULL,
  field_type text NOT NULL,
  section text,
  sort_order int NOT NULL DEFAULT 0,
  select_options text[],
  UNIQUE (category_id, field_key),
  CONSTRAINT program_field_defs_type_check
    CHECK (field_type = ANY (ARRAY['text','number','currency','date','boolean','select']))
);

-- ── programs ─────────────────────────────────────────────────────────────────

ALTER TABLE public.programs ADD COLUMN IF NOT EXISTS category_id bigint REFERENCES public.program_categories(id);
ALTER TABLE public.programs ADD COLUMN IF NOT EXISTS tags text[];
ALTER TABLE public.programs ADD COLUMN IF NOT EXISTS entity text;
ALTER TABLE public.programs ADD COLUMN IF NOT EXISTS account_manager text;
ALTER TABLE public.programs ADD COLUMN IF NOT EXISTS status_narrative text;
ALTER TABLE public.programs ADD COLUMN IF NOT EXISTS percent_complete numeric;
ALTER TABLE public.programs ADD COLUMN IF NOT EXISTS target_completion_date date;
ALTER TABLE public.programs ADD COLUMN IF NOT EXISTS opened_date date;
ALTER TABLE public.programs ADD COLUMN IF NOT EXISTS closed_date date;
ALTER TABLE public.programs ADD COLUMN IF NOT EXISTS custom_fields jsonb NOT NULL DEFAULT '{}'::jsonb;

UPDATE public.programs SET opened_date = (created_at AT TIME ZONE 'America/Chicago')::date WHERE opened_date IS NULL;
ALTER TABLE public.programs ALTER COLUMN opened_date SET DEFAULT CURRENT_DATE;
ALTER TABLE public.programs ALTER COLUMN opened_date SET NOT NULL;

ALTER TABLE public.programs DROP CONSTRAINT IF EXISTS programs_status_check;
UPDATE public.programs SET status = CASE status
  WHEN 'active' THEN 'open'
  WHEN 'draft' THEN 'on_hold'
  WHEN 'archived' THEN 'complete'
  ELSE status
END
WHERE status IN ('active', 'draft', 'archived');
ALTER TABLE public.programs ALTER COLUMN status SET DEFAULT 'open';
ALTER TABLE public.programs ADD CONSTRAINT programs_status_check
  CHECK (status = ANY (ARRAY['open'::text, 'on_hold'::text, 'complete'::text]));

CREATE INDEX IF NOT EXISTS idx_programs_category ON public.programs (category_id);
CREATE INDEX IF NOT EXISTS idx_programs_status ON public.programs (status);
CREATE INDEX IF NOT EXISTS idx_programs_entity ON public.programs (entity);

-- ── program_cars ─────────────────────────────────────────────────────────────

ALTER TABLE public.program_cars ADD COLUMN IF NOT EXISTS status text;
ALTER TABLE public.program_cars ADD COLUMN IF NOT EXISTS joined_date date;
ALTER TABLE public.program_cars ADD COLUMN IF NOT EXISTS exited_date date;
ALTER TABLE public.program_cars ADD COLUMN IF NOT EXISTS rider_external_id_snapshot text;
ALTER TABLE public.program_cars ADD COLUMN IF NOT EXISTS shop_id bigint REFERENCES public.shops(id);
ALTER TABLE public.program_cars ADD COLUMN IF NOT EXISTS scrap_yard_id bigint REFERENCES public.scrap_yards(id);
ALTER TABLE public.program_cars ADD COLUMN IF NOT EXISTS repair_cost_total numeric;
ALTER TABLE public.program_cars ADD COLUMN IF NOT EXISTS custom_fields jsonb NOT NULL DEFAULT '{}'::jsonb;

UPDATE public.program_cars
SET joined_date = (added_at AT TIME ZONE 'America/Chicago')::date
WHERE joined_date IS NULL;
ALTER TABLE public.program_cars ALTER COLUMN joined_date SET DEFAULT CURRENT_DATE;
ALTER TABLE public.program_cars ALTER COLUMN joined_date SET NOT NULL;

-- One open row per (program, car); a car may rejoin after exit, and may sit
-- on more than one program at once.
ALTER TABLE public.program_cars DROP CONSTRAINT IF EXISTS program_cars_program_id_railcar_id_key;
CREATE UNIQUE INDEX IF NOT EXISTS program_cars_open_link_uidx
  ON public.program_cars (program_id, railcar_id)
  WHERE exited_date IS NULL;

CREATE INDEX IF NOT EXISTS idx_program_cars_exited ON public.program_cars (program_id) WHERE exited_date IS NULL;
CREATE INDEX IF NOT EXISTS idx_program_cars_ol_snapshot ON public.program_cars (rider_external_id_snapshot);

-- ── program_documents ────────────────────────────────────────────────────────

ALTER TABLE public.program_documents ADD COLUMN IF NOT EXISTS document_category text;
UPDATE public.program_documents
SET document_category = CASE lower(coalesce(doc_type, ''))
  WHEN 'sow' THEN 'sow'
  WHEN 'car list' THEN 'car_drawing'
  WHEN 'inspection report' THEN 'report'
  WHEN 'photo' THEN 'photo'
  ELSE 'other'
END
WHERE document_category IS NULL;
ALTER TABLE public.program_documents ALTER COLUMN document_category SET DEFAULT 'other';
ALTER TABLE public.program_documents ALTER COLUMN document_category SET NOT NULL;

-- uploaded_by / uploaded_at already exist on the stub table.

-- ── car-line documents + activity ────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.program_car_documents (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  program_car_id bigint NOT NULL REFERENCES public.program_cars(id) ON DELETE CASCADE,
  document_category text NOT NULL DEFAULT 'other',
  file_path text NOT NULL,
  file_name text NOT NULL,
  file_size_bytes bigint,
  uploaded_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  uploaded_at timestamptz NOT NULL DEFAULT now(),
  notes text
);
CREATE INDEX IF NOT EXISTS idx_program_car_documents_car
  ON public.program_car_documents (program_car_id);

CREATE TABLE IF NOT EXISTS public.program_activity (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  program_id bigint NOT NULL REFERENCES public.programs(id) ON DELETE CASCADE,
  program_car_id bigint REFERENCES public.program_cars(id) ON DELETE SET NULL,
  railcar_id bigint REFERENCES public.railcars(id) ON DELETE SET NULL,
  action text NOT NULL,
  detail jsonb NOT NULL DEFAULT '{}'::jsonb,
  actor uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_program_activity_program
  ON public.program_activity (program_id, created_at DESC);

-- ── Seed categories ──────────────────────────────────────────────────────────

INSERT INTO public.program_categories (name, description, sort_order) VALUES
  ('Acquisition', 'New cars entering the fleet', 10),
  ('EOLR (End-of-Lease Return)', 'End-of-lease returns to shop / next assignment', 20),
  ('NLD (New Lessee Delivery)', 'Delivery of cars onto a new lessee', 30),
  ('Sale / Partial Sale', 'Full or partial fleet sales and remarks for sale', 40),
  ('Scrap', 'Cars routed to scrap', 50),
  ('Remark', 'Reporting-mark / number changes', 60),
  ('Qualifications', 'Tank-car and recurring compliance qualifications', 70),
  ('Inspection', 'Shop or field inspections', 80),
  ('Other', 'Catch-all for programs that do not fit a listed category', 90)
ON CONFLICT (name) DO UPDATE
SET description = EXCLUDED.description, sort_order = EXCLUDED.sort_order;

-- ── Seed field defs ──────────────────────────────────────────────────────────

CREATE TEMP TABLE IF NOT EXISTS _pfd (
  category_name text,
  field_key text,
  label text,
  field_type text,
  section text,
  sort_order int,
  select_options text[]
) ON COMMIT DROP;

-- Shared identity / shop / BRC / dispo / trace used by most movement programs
INSERT INTO _pfd (category_name, field_key, label, field_type, section, sort_order, select_options)
SELECT c, k, l, t, s, o, opt
FROM (VALUES
  ('old_reporting_mark', 'Old reporting mark', 'text', 'Car Identity', 10, NULL::text[]),
  ('old_car_number', 'Old car number', 'text', 'Car Identity', 20, NULL::text[]),
  ('new_reporting_mark', 'New reporting mark', 'text', 'Car Identity', 30, NULL::text[]),
  ('new_car_number', 'New car number', 'text', 'Car Identity', 40, NULL::text[]),
  ('pre_registered', 'Pre-registered in Umler', 'boolean', 'Car Identity', 50, NULL::text[]),
  ('arrived_shop_date', 'Arrived shop', 'date', 'Car Status', 10, NULL::text[]),
  ('repair_date', 'Repair date', 'date', 'Car Status', 20, NULL::text[]),
  ('outbound_target_date', 'Outbound target date', 'date', 'Car Status', 30, NULL::text[]),
  ('brc_complete', 'BRC complete', 'boolean', 'BRC Details', 90, NULL::text[]),
  ('original_code6', 'Original Code 6', 'currency', 'BRC Details', 10, NULL::text[]),
  ('original_code7', 'Original Code 7', 'currency', 'BRC Details', 20, NULL::text[]),
  ('original_brc_total', 'Original total BRC', 'currency', 'BRC Details', 30, NULL::text[]),
  ('original_approval_date', 'Original BRC approval', 'date', 'BRC Details', 40, NULL::text[]),
  ('final_code6', 'Final Code 6', 'currency', 'BRC Details', 50, NULL::text[]),
  ('final_code7', 'Final Code 7', 'currency', 'BRC Details', 60, NULL::text[]),
  ('final_brc_total', 'Final total BRC', 'currency', 'BRC Details', 70, NULL::text[]),
  ('final_approval_date', 'Final BRC approval', 'date', 'BRC Details', 80, NULL::text[]),
  ('dispo_requested', 'Dispo requested', 'date', 'End Process', 10, NULL::text[]),
  ('dispo_provided', 'Dispo provided', 'date', 'End Process', 20, NULL::text[]),
  ('dispo_instructions', 'Dispo instructions', 'text', 'End Process', 30, NULL::text[]),
  ('released_from_shop', 'Released from shop', 'date', 'End Process', 40, NULL::text[]),
  ('lease_start_date', 'Lease start date', 'date', 'End Process', 50, NULL::text[]),
  ('arrived_lessee_destination', 'Arrived lessee destination', 'date', 'End Process', 60, NULL::text[]),
  ('trace_date', 'Trace date', 'date', 'Trace Data', 10, NULL::text[]),
  ('trace_city', 'Trace city', 'text', 'Trace Data', 20, NULL::text[]),
  ('trace_state', 'Trace state', 'text', 'Trace Data', 30, NULL::text[]),
  ('trace_loaded_or_empty', 'Loaded or empty', 'select', 'Trace Data', 40, ARRAY['E','L']::text[]),
  ('trace_event_text', 'Trace event', 'text', 'Trace Data', 50, NULL::text[]),
  ('trace_train_id', 'Train ID', 'text', 'Trace Data', 60, NULL::text[]),
  ('trace_destination_city', 'Destination city', 'text', 'Trace Data', 70, NULL::text[]),
  ('trace_destination_state', 'Destination state', 'text', 'Trace Data', 80, NULL::text[]),
  ('trace_reporting_rr', 'Reporting railroad', 'text', 'Trace Data', 90, NULL::text[])
) AS f(k, l, t, s, o, opt)
CROSS JOIN (VALUES
  ('Acquisition'),
  ('EOLR (End-of-Lease Return)'),
  ('NLD (New Lessee Delivery)'),
  ('Sale / Partial Sale'),
  ('Remark'),
  ('Scrap')
) AS cats(c);

INSERT INTO _pfd (category_name, field_key, label, field_type, section, sort_order, select_options)
VALUES
  ('Acquisition', 'nld_to', 'NLD to', 'text', 'Car Identity', 60, NULL::text[]),
  ('Acquisition', 'ras_approval_date', 'RAS approval date', 'date', 'BRC Details', 85, NULL::text[]),
  ('Scrap', 'request_dispo_from_scrapper', 'Request dispo from scrapper', 'date', 'End Process', 5, NULL::text[]),
  ('Scrap', 'umler_sx_request_date', 'Umler SX request', 'date', 'End Process', 70, NULL::text[]),
  ('Scrap', 'umler_sx_response_date', 'Umler SX response', 'date', 'End Process', 80, NULL::text[]);

INSERT INTO _pfd (category_name, field_key, label, field_type, section, sort_order, select_options)
VALUES
  ('Qualifications', 'next_due_year', 'Next due year', 'number', 'Car Status', 10, NULL::text[]),
  ('Qualifications', 'due_for', 'Due for', 'text', 'Car Status', 20, NULL::text[]),
  ('Qualifications', 'arrived_shop_date', 'Shop arrival', 'date', 'Car Status', 30, NULL::text[]),
  ('Qualifications', 'original_code6', 'Code 6', 'currency', 'BRC Details', 10, NULL::text[]),
  ('Qualifications', 'original_code7', 'Code 7', 'currency', 'BRC Details', 20, NULL::text[]),
  ('Qualifications', 'original_brc_total', 'Repair cost total', 'currency', 'BRC Details', 30, NULL::text[]),
  ('Qualifications', 'estimate_approved', 'Estimate approved', 'boolean', 'BRC Details', 40, NULL::text[]),
  ('Qualifications', 'erd', 'ERD', 'date', 'BRC Details', 50, NULL::text[]),
  ('Qualifications', 'brc_complete', 'BRC complete', 'boolean', 'BRC Details', 60, NULL::text[]),
  ('Qualifications', 'released_from_shop', 'Released from shop', 'date', 'End Process', 10, NULL::text[]),
  ('Qualifications', 'dispo_location', 'Dispo location', 'text', 'End Process', 20, NULL::text[]),
  ('Qualifications', 'arrived_dispo_location', 'Arrived dispo location', 'date', 'End Process', 30, NULL::text[]);

INSERT INTO _pfd (category_name, field_key, label, field_type, section, sort_order, select_options)
VALUES
  ('Inspection', 'inspection_date', 'Inspection date', 'date', 'Car Status', 10, NULL::text[]),
  ('Inspection', 'inspection_location', 'Location', 'text', 'Car Status', 20, NULL::text[]),
  ('Inspection', 'defects_identified', 'Defects identified', 'text', 'Car Status', 30, NULL::text[]),
  ('Inspection', 'original_code6', 'Code 6', 'currency', 'BRC Details', 10, NULL::text[]),
  ('Inspection', 'original_code7', 'Code 7', 'currency', 'BRC Details', 20, NULL::text[]),
  ('Inspection', 'original_brc_total', 'BRC total', 'currency', 'BRC Details', 30, NULL::text[]),
  ('Inspection', 'original_approval_date', 'BRC approved', 'date', 'BRC Details', 40, NULL::text[]),
  ('Inspection', 'outbound_target_date', 'Outbound date', 'date', 'Car Status', 40, NULL::text[]),
  ('Inspection', 'ready_for_service', 'Ready for service', 'boolean', 'Car Status', 50, NULL::text[]),
  ('Inspection', 'trace_date', 'Trace date', 'date', 'Trace Data', 10, NULL::text[]),
  ('Inspection', 'trace_city', 'Trace city', 'text', 'Trace Data', 20, NULL::text[]),
  ('Inspection', 'trace_state', 'Trace state', 'text', 'Trace Data', 30, NULL::text[]),
  ('Inspection', 'trace_loaded_or_empty', 'Loaded or empty', 'select', 'Trace Data', 40, ARRAY['E','L']::text[]),
  ('Inspection', 'trace_event_text', 'Trace event', 'text', 'Trace Data', 50, NULL::text[]),
  ('Inspection', 'trace_train_id', 'Train ID', 'text', 'Trace Data', 60, NULL::text[]),
  ('Inspection', 'trace_destination_city', 'Destination city', 'text', 'Trace Data', 70, NULL::text[]),
  ('Inspection', 'trace_destination_state', 'Destination state', 'text', 'Trace Data', 80, NULL::text[]),
  ('Inspection', 'trace_reporting_rr', 'Reporting railroad', 'text', 'Trace Data', 90, NULL::text[]);

INSERT INTO public.program_field_defs (category_id, field_key, label, field_type, section, sort_order, select_options)
SELECT c.id, t.field_key, t.label, t.field_type, t.section, t.sort_order, t.select_options
FROM _pfd t
JOIN public.program_categories c ON c.name = t.category_name
ON CONFLICT (category_id, field_key) DO UPDATE
SET label = EXCLUDED.label,
    field_type = EXCLUDED.field_type,
    section = EXCLUDED.section,
    sort_order = EXCLUDED.sort_order,
    select_options = EXCLUDED.select_options;
