-- Track A step 1: CRM companies / company_products / company_contacts.
-- Additive only. Does not alter accounts structure, master_leases, riders,
-- railcars, or rider_contacts. Comment on accounts is text-only.

-- ============================================================
-- 1. accounts — comment correction only, no structural change
-- ============================================================
COMMENT ON TABLE public.accounts IS
  'One row per active RESIDCO customer/lessee. Prospects and non-customer relationships live in companies, not here.';

-- ============================================================
-- 2. companies
-- ============================================================
CREATE TABLE IF NOT EXISTS public.companies (
  id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name                text NOT NULL,
  relationship_type   text NOT NULL DEFAULT 'unclassified'
                        CHECK (relationship_type IN ('customer','prospect','lessor','railroad','vendor','unclassified','other')),
  account_id          bigint REFERENCES public.accounts(id),
  priority_tier       text CHECK (priority_tier IN ('A','B','C','D')),
  status              text DEFAULT 'target'
                        CHECK (status IN ('target','contacted','in_discussion','lost','won')),
  merged_into_id      bigint REFERENCES public.companies(id),
  source              text NOT NULL DEFAULT 'manual',
  notes               text,
  created_at          timestamptz NOT NULL DEFAULT now(),
  updated_at          timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT companies_customer_requires_account
    CHECK (
      (relationship_type = 'customer' AND account_id IS NOT NULL)
      OR (relationship_type <> 'customer' AND account_id IS NULL)
    )
);

CREATE INDEX IF NOT EXISTS idx_companies_account ON public.companies(account_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_companies_account_unique ON public.companies(account_id) WHERE account_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_companies_merged_into ON public.companies(merged_into_id) WHERE merged_into_id IS NOT NULL;

COMMENT ON TABLE public.companies IS
  'CRM entity for prospects, lessors, and other non-lease relationships. A row becomes a real customer by setting account_id + relationship_type = customer together (enforced by companies_customer_requires_account). merged_into_id marks a row absorbed into another during dedup review — never hard-deleted.';
COMMENT ON COLUMN public.companies.relationship_type IS
  'customer requires account_id set (and vice versa) — see companies_customer_requires_account. unclassified is the default for anything not yet reviewed (e.g. an Outlook-origin contact with no match, or a freshly imported row pending the matching/merge review queue).';
COMMENT ON COLUMN public.companies.merged_into_id IS
  'Set when this row was merged into another during dedup review. Rows with this set are inactive: excluded from search and from the matching queue, but never deleted — keeps history intact.';

DROP TRIGGER IF EXISTS trg_companies_updated_at ON public.companies;
CREATE TRIGGER trg_companies_updated_at
  BEFORE UPDATE ON public.companies
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- ============================================================
-- 3. company_products
-- ============================================================
CREATE TABLE IF NOT EXISTS public.company_products (
  id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id          bigint NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
  commodity_family    text,
  product             text,
  estimated_railcars  integer,
  car_type            text,
  size                text,
  round_or_trough     text,
  created_at          timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_company_products_company ON public.company_products(company_id);

COMMENT ON TABLE public.company_products IS
  'One row per product/commodity line for a company (a single company can have several — e.g. multiple rows in the source Company & Product workbook tab). Do not add commodity/car-type/estimated-railcar columns to companies itself; they belong here.';

-- ============================================================
-- 4. company_contacts — distinct from rider_contacts
-- ============================================================
CREATE TABLE IF NOT EXISTS public.company_contacts (
  id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id          bigint NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
  name                text NOT NULL,
  title               text,
  department          text,
  email               text,
  phone               text,
  mobile              text,
  alt_phone           text,
  street              text,
  city                text,
  state               text,
  zip                 text,
  linkedin_url        text,
  linkedin_job_title  text,
  function_role       text,
  is_primary          boolean NOT NULL DEFAULT false,
  notes               text,
  outlook_contact_id  text,
  custom_fields       jsonb NOT NULL DEFAULT '{}'::jsonb,
  source              text NOT NULL DEFAULT 'manual',
  created_at          timestamptz NOT NULL DEFAULT now(),
  updated_at          timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_company_contacts_outlook_id
  ON public.company_contacts(outlook_contact_id) WHERE outlook_contact_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_company_contacts_company ON public.company_contacts(company_id);

COMMENT ON TABLE public.company_contacts IS
  'People at a company (prospect, lessor, or — once companies.account_id is set — a real customer). NOT the same table as rider_contacts, which is OL-level lease-ops contacts served by the existing #/contacts and /api/contacts — that table and route are unchanged by this migration.';
COMMENT ON COLUMN public.company_contacts.custom_fields IS
  'Provider-specific fields that do not warrant their own column (e.g. FindUs.Rail/MARK Contacts extras: branch area, rail primary/secondary/third, locomotive, ID/status, misc, spouse, interests, alt email, fax, home phone, phone extensions, web site). Keeps the table from growing a column per data source.';

DROP TRIGGER IF EXISTS trg_company_contacts_updated_at ON public.company_contacts;
CREATE TRIGGER trg_company_contacts_updated_at
  BEFORE UPDATE ON public.company_contacts
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();
