-- Append-only history for guarded Car Status Inactive / Reactivate transitions.
-- Does not alter any existing railcars rows.

CREATE TABLE IF NOT EXISTS car_status_history (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  car_id bigint NOT NULL REFERENCES railcars (id) ON DELETE CASCADE,
  event_type text NOT NULL,
  reason text NOT NULL,
  created_by text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  from_status text,
  to_status text,
  CONSTRAINT car_status_history_event_type_check
    CHECK (event_type = ANY (ARRAY['marked_inactive'::text, 'reactivated'::text]))
);

CREATE INDEX IF NOT EXISTS idx_car_status_history_car_id_created
  ON car_status_history (car_id, created_at DESC);

COMMENT ON TABLE car_status_history IS
  'Append-only Inactive / Reactivate reasons. Separate from rent_events (on/off rent KPIs).';
