-- New Acquisitions bulk loader: batch identity + per-car acquisition fields.
-- Insert-only importer; never updates existing railcars. Safe to re-run.

CREATE TABLE IF NOT EXISTS public.acquisition_batches (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  label text NOT NULL,
  acquisition_date date NOT NULL,
  entity text NOT NULL,
  default_purchase_price numeric,
  default_rental_status text NOT NULL DEFAULT 'Idle',
  created_by text,
  created_at timestamptz NOT NULL DEFAULT now(),
  car_count integer NOT NULL DEFAULT 0,
  CONSTRAINT acquisition_batches_entity_check
    CHECK (entity IN ('Main', 'Rail Partners Select', 'Coal')),
  CONSTRAINT acquisition_batches_rental_status_check
    CHECK (default_rental_status IN ('Leased', 'Idle', 'Sold', 'Abatement'))
);

CREATE INDEX IF NOT EXISTS idx_acquisition_batches_created_at
  ON public.acquisition_batches (created_at DESC);

ALTER TABLE public.railcars
  ADD COLUMN IF NOT EXISTS acquisition_batch_id bigint REFERENCES public.acquisition_batches(id);

ALTER TABLE public.railcars
  ADD COLUMN IF NOT EXISTS acquisition_date date;

ALTER TABLE public.railcars
  ADD COLUMN IF NOT EXISTS purchase_price numeric;

ALTER TABLE public.railcars
  ADD COLUMN IF NOT EXISTS needs_completion boolean NOT NULL DEFAULT false;

CREATE INDEX IF NOT EXISTS idx_railcars_acquisition_batch
  ON public.railcars (acquisition_batch_id)
  WHERE acquisition_batch_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_railcars_needs_completion
  ON public.railcars (needs_completion)
  WHERE needs_completion IS TRUE;
