-- Contacts 360: trigram search, lease links, fleet stats, attachments provenance.
-- Additive only. Does not alter accounts, master_leases, riders, or railcars columns.

CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE INDEX IF NOT EXISTS idx_companies_name_trgm
  ON public.companies USING gin (name gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_company_contacts_name_trgm
  ON public.company_contacts USING gin (name gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_company_contacts_email_trgm
  ON public.company_contacts USING gin (email gin_trgm_ops);

CREATE TABLE IF NOT EXISTS public.contact_lease_links (
  id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_contact_id bigint NOT NULL REFERENCES public.company_contacts(id) ON DELETE CASCADE,
  master_lease_id    bigint REFERENCES public.master_leases(id) ON DELETE CASCADE,
  rider_id           bigint REFERENCES public.riders(id) ON DELETE CASCADE,
  relationship_note  text,
  created_by         uuid REFERENCES auth.users(id),
  created_at         timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT contact_lease_links_target CHECK (
    (master_lease_id IS NOT NULL) OR (rider_id IS NOT NULL)
  )
);
CREATE INDEX IF NOT EXISTS idx_contact_lease_links_contact ON public.contact_lease_links(company_contact_id);
CREATE INDEX IF NOT EXISTS idx_contact_lease_links_mla ON public.contact_lease_links(master_lease_id) WHERE master_lease_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_contact_lease_links_rider ON public.contact_lease_links(rider_id) WHERE rider_id IS NOT NULL;

COMMENT ON TABLE public.contact_lease_links IS
  'Many-to-many link from company_contacts to an MLA and/or OL. Does not alter master_leases or riders.';

CREATE TABLE IF NOT EXISTS public.company_fleet_stats (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id   bigint NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
  car_type     text NOT NULL,
  fleet_size   integer NOT NULL,
  as_of_date   date,
  source       text NOT NULL DEFAULT 'manual',
  created_at   timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_company_fleet_stats_company ON public.company_fleet_stats(company_id);

COMMENT ON TABLE public.company_fleet_stats IS
  'Fleet size by car type for a company (Lessors import / manual). Empty until that import runs.';

ALTER TABLE public.attachments
  DROP CONSTRAINT IF EXISTS attachments_source_module_check;
ALTER TABLE public.attachments
  ADD CONSTRAINT attachments_source_module_check
  CHECK (source_module IN ('manual','account_transitions','lease_management','programs','contacts_directory'));

ALTER TABLE public.attachments
  DROP CONSTRAINT IF EXISTS attachments_entity_type_check;
ALTER TABLE public.attachments
  ADD CONSTRAINT attachments_entity_type_check
  CHECK (entity_type IN ('master_lease','rider','railcar','account','company','company_contact'));
