WITH src(account_id, to_am) AS (
  VALUES
  (144::bigint, 'BH'::text),
  (61::bigint, 'FF'::text),
  (86::bigint, 'BH'::text),
  (114::bigint, 'FF'::text),
  (118::bigint, 'BH'::text),
  (157::bigint, 'BH'::text),
  (205::bigint, 'BH'::text),
  (173::bigint, 'FF'::text),
  (248::bigint, 'FF'::text),
  (69::bigint, 'FF'::text),
  (32::bigint, 'FF'::text),
  (68::bigint, 'FF'::text),
  (127::bigint, 'FF'::text),
  (44::bigint, 'FF'::text),
  (103::bigint, 'FF'::text),
  (121::bigint, 'BH'::text),
  (153::bigint, 'FF'::text),
  (218::bigint, 'BH'::text),
  (8::bigint, 'FF'::text),
  (264::bigint, 'FF'::text),
  (10::bigint, 'FF'::text),
  (181::bigint, 'FF'::text),
  (212::bigint, 'BH'::text),
  (13::bigint, 'BH'::text),
  (57::bigint, 'BH'::text),
  (50::bigint, 'BH'::text),
  (176::bigint, 'BH'::text),
  (251::bigint, 'FF'::text),
  (163::bigint, 'BH'::text),
  (146::bigint, 'FF'::text),
  (204::bigint, 'BH'::text),
  (21::bigint, 'FF'::text),
  (236::bigint, 'FF'::text),
  (123::bigint, 'BH'::text),
  (187::bigint, 'FF'::text),
  (132::bigint, 'FF'::text),
  (85::bigint, 'BH'::text),
  (238::bigint, 'FF'::text),
  (262::bigint, 'FF'::text),
  (185::bigint, 'FF'::text),
  (241::bigint, 'FF'::text),
  (105::bigint, 'FF'::text),
  (154::bigint, 'FF'::text),
  (55::bigint, 'FF'::text),
  (252::bigint, 'BH'::text),
  (193::bigint, 'BH'::text),
  (75::bigint, 'FF'::text),
  (166::bigint, 'FF'::text),
  (208::bigint, 'BH'::text),
  (250::bigint, 'FF'::text),
  (266::bigint, 'FF'::text),
  (97::bigint, 'FF'::text),
  (203::bigint, 'FF'::text),
  (189::bigint, 'BH'::text),
  (261::bigint, 'FF'::text),
  (174::bigint, 'BH'::text),
  (191::bigint, 'FF'::text),
  (232::bigint, 'BH'::text),
  (41::bigint, 'BH'::text),
  (165::bigint, 'FF'::text),
  (42::bigint, 'FF'::text),
  (73::bigint, 'BH'::text),
  (58::bigint, 'BH'::text),
  (49::bigint, 'BH'::text),
  (38::bigint, 'FF'::text),
  (160::bigint, 'FF'::text),
  (190::bigint, 'FF'::text),
  (87::bigint, 'BH'::text),
  (79::bigint, 'BH'::text),
  (213::bigint, 'FF'::text),
  (71::bigint, 'FF'::text),
  (227::bigint, 'FF'::text),
  (229::bigint, 'FF'::text),
  (17::bigint, 'FF'::text),
  (43::bigint, 'BH'::text),
  (224::bigint, 'BH'::text),
  (151::bigint, 'FF'::text),
  (6::bigint, 'BH'::text),
  (124::bigint, 'BH'::text),
  (14::bigint, 'BH'::text),
  (52::bigint, 'BH'::text),
  (74::bigint, 'FF'::text),
  (119::bigint, 'FF'::text),
  (239::bigint, 'FF'::text),
  (260::bigint, 'FF'::text),
  (34::bigint, 'FF'::text),
  (256::bigint, 'BH'::text),
  (199::bigint, 'FF'::text),
  (83::bigint, 'FF'::text),
  (101::bigint, 'FF'::text),
  (110::bigint, 'FF'::text),
  (47::bigint, 'BH'::text),
  (128::bigint, 'FF'::text),
  (96::bigint, 'BH'::text),
  (129::bigint, 'BH'::text),
  (25::bigint, 'BH'::text),
  (141::bigint, 'BH'::text),
  (237::bigint, 'FF'::text),
  (136::bigint, 'BH'::text),
  (168::bigint, 'BH'::text),
  (149::bigint, 'FF'::text),
  (5::bigint, 'BH'::text),
  (180::bigint, 'BH'::text),
  (226::bigint, 'FF'::text),
  (116::bigint, 'FF'::text),
  (81::bigint, 'FF'::text),
  (263::bigint, 'FF'::text),
  (140::bigint, 'FF'::text),
  (225::bigint, 'BH'::text),
  (257::bigint, 'BH'::text),
  (156::bigint, 'BH'::text),
  (145::bigint, 'FF'::text),
  (206::bigint, 'FF'::text),
  (80::bigint, 'FF'::text),
  (184::bigint, 'FF'::text),
  (65::bigint, 'FF'::text),
  (19::bigint, 'BH'::text),
  (152::bigint, 'BH'::text),
  (167::bigint, 'BH'::text),
  (170::bigint, 'BH'::text),
  (72::bigint, 'FF'::text),
  (112::bigint, 'FF'::text),
  (242::bigint, 'BH'::text),
  (192::bigint, 'FF'::text),
  (253::bigint, 'FF'::text),
  (91::bigint, 'BH'::text),
  (23::bigint, 'BH'::text),
  (202::bigint, 'BH'::text),
  (115::bigint, 'BH'::text),
  (254::bigint, 'FF'::text),
  (209::bigint, 'FF'::text),
  (139::bigint, 'BH'::text),
  (70::bigint, 'FF'::text),
  (40::bigint, 'BH'::text),
  (188::bigint, 'BH'::text),
  (194::bigint, 'FF'::text),
  (63::bigint, 'BH'::text),
  (210::bigint, 'FF'::text),
  (162::bigint, 'BH'::text),
  (230::bigint, 'BH'::text),
  (82::bigint, 'BH'::text),
  (179::bigint, 'BH'::text),
  (104::bigint, 'BH'::text),
  (211::bigint, 'BH'::text),
  (161::bigint, 'FF'::text),
  (195::bigint, 'FF'::text),
  (107::bigint, 'BH'::text),
  (269::bigint, 'BH'::text),
  (201::bigint, 'BH'::text),
  (234::bigint, 'BH'::text),
  (137::bigint, 'FF'::text),
  (122::bigint, 'FF'::text),
  (2::bigint, 'FF'::text),
  (215::bigint, 'BH'::text),
  (67::bigint, 'FF'::text),
  (102::bigint, 'FF'::text),
  (31::bigint, 'FF'::text),
  (148::bigint, 'FF'::text),
  (143::bigint, 'BH'::text),
  (158::bigint, 'BH'::text),
  (159::bigint, 'FF'::text),
  (106::bigint, 'FF'::text),
  (54::bigint, 'FF'::text),
  (183::bigint, 'FF'::text),
  (77::bigint, 'BH'::text)
),
deleted AS (
  DELETE FROM account_transition_records RETURNING id
),
ins AS (
  INSERT INTO account_transition_records (account_id, from_account_manager, to_account_manager, status)
  SELECT s.account_id, nullif(btrim(a.account_manager), ''), s.to_am, 'open'
  FROM src s
  JOIN accounts a ON a.id = s.account_id
  RETURNING id, account_id, to_account_manager
)
SELECT
  (SELECT count(*) FROM deleted) AS deleted_rows,
  (SELECT count(*) FROM ins) AS inserted_rows,
  (SELECT count(*) FROM ins WHERE to_account_manager = 'BH') AS to_bh,
  (SELECT count(*) FROM ins WHERE to_account_manager = 'FF') AS to_ff,
  (SELECT count(*) FROM src s LEFT JOIN accounts a ON a.id = s.account_id WHERE a.id IS NULL) AS missing_ids;
