-- Sequences
BEGIN;
CREATE SEQUENCE IF NOT EXISTS "assignment_history_id_seq";
CREATE SEQUENCE IF NOT EXISTS "attachments_id_seq";
CREATE SEQUENCE IF NOT EXISTS "car_number_history_id_seq";
CREATE SEQUENCE IF NOT EXISTS "dv_ab_codes_id_seq";
CREATE SEQUENCE IF NOT EXISTS "dv_calculation_ab_items_id_seq";
CREATE SEQUENCE IF NOT EXISTS "dv_calculations_id_seq";
CREATE SEQUENCE IF NOT EXISTS "dv_car_dep_rates_id_seq";
CREATE SEQUENCE IF NOT EXISTS "dv_cost_factors_id_seq";
CREATE SEQUENCE IF NOT EXISTS "dv_salvage_quarters_id_seq";
CREATE SEQUENCE IF NOT EXISTS "master_leases_id_seq";
CREATE SEQUENCE IF NOT EXISTS "program_cars_id_seq";
CREATE SEQUENCE IF NOT EXISTS "program_documents_id_seq";
CREATE SEQUENCE IF NOT EXISTS "programs_id_seq";
CREATE SEQUENCE IF NOT EXISTS "railcar_assignments_id_seq";
CREATE SEQUENCE IF NOT EXISTS "railcars_id_seq";
CREATE SEQUENCE IF NOT EXISTS "rent_events_id_seq";
CREATE SEQUENCE IF NOT EXISTS "rider_contacts_id_seq";
CREATE SEQUENCE IF NOT EXISTS "riders_id_seq";
CREATE SEQUENCE IF NOT EXISTS "user_column_prefs_id_seq";
SELECT setval('"assignment_history_id_seq"', 8, true);
SELECT setval('"attachments_id_seq"', 4, true);
SELECT setval('"car_number_history_id_seq"', 1, false);
SELECT setval('"dv_ab_codes_id_seq"', 18, true);
SELECT setval('"dv_calculation_ab_items_id_seq"', 1, true);
SELECT setval('"dv_calculations_id_seq"', 1, true);
SELECT setval('"dv_car_dep_rates_id_seq"', 6, true);
SELECT setval('"dv_cost_factors_id_seq"', 70, true);
SELECT setval('"dv_salvage_quarters_id_seq"', 90, true);
SELECT setval('"master_leases_id_seq"', 189, true);
SELECT setval('"program_cars_id_seq"', 1, false);
SELECT setval('"program_documents_id_seq"', 1, false);
SELECT setval('"programs_id_seq"', 1, false);
SELECT setval('"railcar_assignments_id_seq"', 14938, true);
SELECT setval('"railcars_id_seq"', 15500, true);
SELECT setval('"rent_events_id_seq"', 1, false);
SELECT setval('"rider_contacts_id_seq"', 1, false);
SELECT setval('"riders_id_seq"', 293, true);
SELECT setval('"user_column_prefs_id_seq"', 8, true);
COMMIT;